on: [push, pull_request]

name: Static Analysis
jobs:
  syntax-compat:
    name: Syntax Compatibility (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check syntax compatibility
        run: python -m compileall -q lutris/

  mypy-checker:
    name: Mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print current dir
        run: pwd
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Ubuntu dependencies
        run: |
          sudo apt update
          sudo apt-get install libdbus-1-dev pkg-config libgirepository-2.0-dev python3-gi-cairo libcairo2-dev
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          make req-python
          make dev
      - name: Run mypy analysis
        run: |
          mypy --version
          mypy . --python-version 3.8

  ruff-checker:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          make dev
      - name: Check code style
        run: ruff --version
          ruff check .
      - name: Check format
        run: ruff format . --check
